on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.json
      - run: mv ./common.oas2.yml ./swagger-ui/common.oas2.yml
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui